name: Generate Sitemap & Deploy

on:
  schedule:
    - cron: '0 3 * * *' # chạy lúc 03:00 UTC mỗi ngày (~10h sáng VN)
  workflow_dispatch: # có thể chạy thủ công
  push:
    branches: [main] # khi bạn push code

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Generate sitemap
        run: npm run generate-sitemap

      - name: Commit & push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/sitemap.xml
          git commit -m "chore: update sitemap [bot]" || echo "No changes"
          git push
