name: Generate Sitemap & Deploy

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate sitemap
        run: yarn generate-sitemap

      - name: Commit & push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/sitemap.xml
          git commit -m "chore: update sitemap [bot]" || echo "No changes to commit"
          git push
